---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r install needed}
#install.packages("tidyve")
#install.packages("reshape2")
#install.packages("ggplot2") 
#install.packages("gridExtra")
#install.packages("scales")
```

```{r, Librarys}
library(tidyverse) 
library(reshape2)
library(ggplot2)
library(gridExtra)
library(scales)
```

```{r pega diretorio local}
script_dir = dirname(rstudioapi::getActiveDocumentContext()$path)
#cria o diretorio para output
if (!dir.exists(paste0(script_dir,"/","VISITAS_AEDES_2012_NOV2020"))) {dir.create(paste0(script_dir,"/","VISITAS_AEDES_2012_NOV2020"))}

```

```{r Load CSVs}
#UPDATE
file <- paste0(script_dir,"/2012_2020_tratado.csv")

#Verifica a codificação LINUX
encode <- as.character(read.table(pipe(paste("uchardet ",file))))
#Lê os dados

ACOES <- read.csv2(
  file ,
  fileEncoding=encode, 
  header =TRUE ,
  sep=";",
  skipNul=TRUE,
  dec=",",
  na.strings=c("NA","NaN", " ",""))

#data[] <- 
#cria bkp original
ACOESBKP <- ACOES 

#verifica
#sapply(ACOES, class)

#convert numerico
for(i in c(seq(2,15))){
ACOES[,i] <- gsub("\\.", "", ACOES[,i])
ACOES[,i] <- as.numeric(as.character(ACOES[,i]))
}

#verifica
#sapply(A, class)

```



```{r função para imagens}


DISTRI <-
function(X){

#filtra por distrito    
ACOES_TMP <-
  ACOES %>%
    filter(Distrito == X)

#lista de colunas
lista <- 
  names(
    ACOES_TMP %>%
      select(!Distrito) %>%
      select(!Ano))




#loop pela lista
for(i in lista){

value<-
  ACOES_TMP %>%
     select(Ano,i) #%>%

#cria outuput dir
##pegando o diretorio do script
if (!dir.exists(paste0(script_dir,"/","VISITAS_AEDES_2012_NOV2020","/",X))) {dir.create(paste0(script_dir,"/","VISITAS_AEDES_2012_NOV2020","/",X))}

#plota tudo    
plot<-
  value %>%
    ggplot( aes(x = Ano,y= value[,2])) +
      ylab(gsub('\\.', ' ', i))+
      geom_line()+
      geom_point() +
  #muda de cientifico para padrão original da lista  
      scale_y_continuous(labels = comma_format(big.mark = ".",
                                           decimal.mark = ",")) +
      ggtitle("VISITAS_AEDES_2012_NOV2020.XLSX")+
      ggsave(paste0(script_dir,"/","VISITAS_AEDES_2012_NOV2020","/",X,"/",gsub('\\.', ' ', i),".png"))

  }
}

```


```{r teste}

#filtra por distrito    
  ACOES_MUNICIPIO <-
    ACOES %>% 
    filter(!grepl("TOTAL",Distrito)) %>%
    filter(!grepl("TOTAL",Ano)) %>%
    select(!Distrito) %>%
    group_by(Ano) %>%
#  summarise_all(sum,is.na(1))
summarise_if(is.numeric, sum,na.rm=T)

unique(ACOESBKP$Ano)


#lista de colunas
lista <- 
  names(
    ACOES %>%
      select(!Distrito) %>%
      select(!Ano)) 
  



#loop pela lista
for(i in lista){

value<-
  ACOES_MUNICIPIO %>%
     select(Ano,i) %>%
     filter(!is.na(Ano))




#cria outuput dir
##pegando o diretorio do script
if (!dir.exists(paste0(script_dir,"/","VISITAS_AEDES_2012_NOV2020","/","Município"))) {dir.create(paste0(script_dir,"/","VISITAS_AEDES_2012_NOV2020","/","Município"))}

#plota tudo    
plot<-
  as.data.frame(value) %>% 
    ggplot( aes(x = Ano,y=.[,2])) +
      ylab(gsub('\\.', ' ', i))+
      geom_line()+
      geom_point() +
#muda de cientifico para padrão original da lista  
      scale_y_continuous(labels = comma_format(big.mark = ".",
                                           decimal.mark = ",")) +
      ggtitle("VISITAS_AEDES_2012_NOV2020.XLSX")+
      ggsave(paste0(script_dir,"/","VISITAS_AEDES_2012_NOV2020","/","Município","/",gsub('\\.', ' ', i),".png"))

}

```


```{r chama a função}

DISTRI("Alto de Pinheiros")
DISTRI("Pinheiros")
DISTRI("Jardim Paulista")
DISTRI("Itaim Bibi")


```

